// Reopen the real paper generated by `npm run test:live-mineru` without parsing it again.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { _electron: electron } = require('playwright-core');

async function run() {
  const liveTranslate = process.argv.includes('--translate');
  const root = path.resolve(__dirname, '..');
  const artifacts = path.join(root, 'test-artifacts');
  const source = path.join(artifacts, 'live-mineru-workspace');
  const workspace = path.join(artifacts, 'reopen-mineru-workspace');
  if (!path.resolve(workspace).startsWith(path.resolve(artifacts) + path.sep)) throw new Error('Unexpected workspace path');
  const papers = fs.readdirSync(path.join(source, 'papers')).filter(name => name.endsWith('.json'));
  assert.ok(papers.length > 0, 'Run npm run test:live-mineru first.');
  fs.rmSync(workspace, { recursive: true, force: true });
  fs.mkdirSync(path.join(workspace, 'papers'), { recursive: true });
  const savedPaper = JSON.parse(fs.readFileSync(path.join(source, 'papers', papers[0]), 'utf8'));
  const { parsedMarkdownBlocks } = await import('../src/academicMarkdown.mjs');
  const blocks = parsedMarkdownBlocks(savedPaper.mineruMarkdown);
  assert.equal(blocks.filter(block => block.resource && block.sourceMarkdown.startsWith('![')).length, 5);
  assert.equal(blocks.filter(block => block.resource && block.sourceMarkdown.startsWith('<table')).length, 4);
  assert.ok(blocks.some(block => !block.resource && block.text.startsWith('Figure 1:')));
  assert.ok(blocks.some(block => !block.resource && block.text.startsWith('Table 1:')));
  fs.writeFileSync(path.join(workspace, 'papers', papers[0]), JSON.stringify({
    ...savedPaper, blocks, mineruBlocks: blocks, position: { ...savedPaper.position, tab: 'Paper', block: 1 }
  }));
  fs.writeFileSync(path.join(workspace, 'settings.json'), JSON.stringify({ autoCheckUpdates: false, onboardingCompletedVersion: 1 }));
  const app = await electron.launch({ args: ['.'], cwd: root, env: { ...process.env, NODE_ENV: 'production', PAPERBRIDGE_WORKSPACE: workspace }, timeout: 30000 });
  try {
    const page = await app.firstWindow();
    await page.setViewportSize({ width: 1320, height: 820 });
    await page.getByRole('button', { name: 'Paper', exact: true }).click();
    await page.locator('.document-preview').waitFor();
    const preview = {
      superscripts: await page.locator('.document-preview sup').count(),
      tables: await page.locator('.document-preview table').count(),
      figures: await page.locator('.document-preview img[src^="data:image/"]').count(),
      formulas: await page.locator('.document-preview .katex-display').count()
    };
    assert.ok(preview.superscripts >= 5);
    assert.ok(preview.tables >= 1);
    assert.ok(preview.figures >= 1);
    assert.ok(preview.formulas >= 1);
    await page.getByRole('button', { name: 'Reader', exact: true }).click();
    const reader = {
      superscripts: await page.locator('.reader-list sup').count(),
      tables: await page.locator('.reader-list table').count(),
      figures: await page.locator('.reader-list img[src^="data:image/"]').count(),
      formulas: await page.locator('.reader-list .katex-display').count()
    };
    assert.ok(reader.superscripts >= 5);
    assert.ok(reader.tables >= 1);
    assert.ok(reader.figures >= 1);
    assert.ok(reader.formulas >= 1);
    assert.equal(await page.locator('#block-3 .source-text').innerText().then(text => text.includes('<sup>')), false);
    await page.evaluate(() => {
      const paragraph = document.querySelector('#block-3 .source-text p');
      const range = document.createRange();
      range.setStart(paragraph.firstChild, 7);
      range.setEnd(paragraph.querySelector('sup').firstChild, 1);
      const selected = window.getSelection(); selected.removeAllRanges(); selected.addRange(range);
      paragraph.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));
    });
    await page.getByText('SELECTED TEXT · BLOCK 3', { exact: true }).waitFor();
    await page.locator('.inspector .highlight.blue').click();
    assert.equal(await page.evaluate(() => CSS.highlights.get('paperbridge-blue')?.size), 1);
    let captionTranslation = '';
    let tableCaptionTranslation = '';
    let modelVramGiB = null;
    if (liveTranslate) {
      const caption = blocks.find(block => block.text.startsWith('Figure 1:'));
      const image = blocks.find(block => block.resource && block.sourceMarkdown.startsWith('!['));
      const tableCaption = blocks.find(block => block.text.startsWith('Table 1:'));
      const table = blocks.find(block => block.resource && block.sourceMarkdown.startsWith('<table'));
      assert.ok(caption && image && tableCaption && table);
      await page.locator(`#block-${caption.id} button[title="Translate or retry block"]`).click();
      await page.locator(`#block-${caption.id} .translation-text.done`).waitFor({ timeout: 120000 });
      captionTranslation = await page.locator(`#block-${caption.id} .translation-text.done`).innerText();
      assert.ok(captionTranslation.trim().length > 5);
      await page.locator(`#block-${tableCaption.id} button[title="Translate or retry block"]`).click();
      await page.locator(`#block-${tableCaption.id} .translation-text.done`).waitFor({ timeout: 120000 });
      tableCaptionTranslation = await page.locator(`#block-${tableCaption.id} .translation-text.done`).innerText();
      assert.ok(tableCaptionTranslation.trim().length > 5);
      assert.equal(await page.locator(`#block-${image.id} .translation-text`).count(), 0);
      assert.equal(await page.locator(`#block-${table.id} .translation-text`).count(), 0);
      const after = JSON.parse(fs.readFileSync(path.join(workspace, 'papers', papers[0]), 'utf8'));
      assert.equal(after.blocks[image.id - 1].sourceMarkdown, image.sourceMarkdown);
      assert.equal(after.blocks[image.id - 1].translation, '');
      assert.equal(after.blocks[table.id - 1].sourceMarkdown, table.sourceMarkdown);
      assert.equal(after.blocks[table.id - 1].translation, '');
      assert.equal(await page.locator('.selection-toolbar').count(), 0, 'The floating selection toolbar should close after scrolling.');
      const running = await fetch('http://127.0.0.1:11434/api/ps').then(response => response.json());
      const model = running.models?.find(item => item.name === 'translategemma:4b');
      modelVramGiB = model ? Number(((model.size_vram || 0) / 1024 ** 3).toFixed(2)) : null;
      assert.ok(modelVramGiB > 0, 'Ollama did not report the translation model in GPU VRAM.');
    }
    await page.screenshot({ path: path.join(artifacts, 'live-mineru-reader-after.png') });
    console.log(JSON.stringify({ blocks: blocks.length, resources: blocks.filter(block => block.resource).length, preview, reader, selected: await page.locator('.inspector blockquote').innerText(), captionTranslation, tableCaptionTranslation, modelVramGiB }, null, 2));
  } finally {
    await app.close();
    fs.rmSync(workspace, { recursive: true, force: true });
  }
}

run().catch(error => { console.error(error); process.exitCode = 1; });
